/**
 * openapi-to-mcp.ts
 *
 * Generates MCP tool stubs from an OpenAPI 3.x spec.
 * Reads from a local JSON file or URL and prints TypeScript tool definitions
 * to stdout that you can paste into your src/tools/ file.
 *
 * Usage:
 *   npx tsx scripts/openapi-to-mcp.ts ./openapi.json
 *   npx tsx scripts/openapi-to-mcp.ts https://petstore3.swagger.io/api/v3/openapi.json
 */

import { readFileSync } from "fs";

type OpenAPISpec = {
  paths: Record<
    string,
    Record<
      string,
      {
        operationId?: string;
        summary?: string;
        description?: string;
        parameters?: Array<{
          name: string;
          in: string;
          required?: boolean;
          description?: string;
          schema?: { type?: string; enum?: string[] };
        }>;
        requestBody?: {
          required?: boolean;
          content?: {
            "application/json"?: {
              schema?: {
                properties?: Record<
                  string,
                  { type?: string; description?: string }
                >;
                required?: string[];
              };
            };
          };
        };
      }
    >
  >;
};

function toSnakeCase(s: string): string {
  return s.replace(/([A-Z])/g, "_$1").toLowerCase().replace(/^_/, "");
}

function toToolName(operationId: string | undefined, method: string, path: string): string {
  if (operationId) return toSnakeCase(operationId);
  const parts = path.replace(/[{}]/g, "").split("/").filter(Boolean);
  return `${method}_${parts.join("_")}`;
}

async function main() {
  const arg = process.argv[2];
  if (!arg) {
    console.error("Usage: tsx scripts/openapi-to-mcp.ts <path-or-url>");
    process.exit(1);
  }

  let raw: string;
  if (arg.startsWith("http")) {
    const res = await fetch(arg);
    raw = await res.text();
  } else {
    raw = readFileSync(arg, "utf-8");
  }

  const spec: OpenAPISpec = JSON.parse(raw);
  const tools: string[] = [];

  for (const [path, methods] of Object.entries(spec.paths ?? {})) {
    for (const [method, op] of Object.entries(methods)) {
      if (["get", "post", "put", "patch", "delete"].indexOf(method) === -1) continue;

      const toolName = toToolName(op.operationId, method, path);
      const description = op.summary ?? op.description ?? `${method.toUpperCase()} ${path}`;

      // Build inputSchema properties from path/query params and request body
      const properties: Record<string, { type: string; description?: string; enum?: string[] }> = {};
      const required: string[] = [];

      for (const param of op.parameters ?? []) {
        if (param.in === "path" || param.in === "query") {
          properties[param.name] = {
            type: param.schema?.type ?? "string",
            description: param.description,
            ...(param.schema?.enum ? { enum: param.schema.enum } : {}),
          };
          if (param.required) required.push(param.name);
        }
      }

      const bodySchema =
        op.requestBody?.content?.["application/json"]?.schema;
      if (bodySchema?.properties) {
        for (const [propName, prop] of Object.entries(bodySchema.properties)) {
          properties[propName] = {
            type: prop.type ?? "string",
            description: prop.description,
          };
        }
        if (op.requestBody?.required && bodySchema.required) {
          required.push(...bodySchema.required);
        }
      }

      const propsJson = JSON.stringify(properties, null, 6)
        .split("\n")
        .join("\n    ");
      const requiredJson = JSON.stringify([...new Set(required)]);

      tools.push(`  {
    name: "${toolName}",
    description: "${description.replace(/"/g, '\\"')}",
    inputSchema: {
      type: "object",
      properties: ${propsJson},
      required: ${requiredJson},
    },
  },`);
    }
  }

  console.log(`// Auto-generated by openapi-to-mcp.ts — review before using
// Source: ${arg}

export const generatedTools = [
${tools.join("\n")}
];

export async function handleGeneratedTool(
  name: string,
  args: Record<string, unknown>
) {
  // TODO: implement each tool handler
  // Pattern: fetch(\`\${BASE_URL}/your-endpoint\`, { headers: authHeaders() })
  throw new Error(\`Not implemented: \${name}\`);
}
`);
}

main().catch(console.error);
