"""
openapi_to_mcp.py

Generates MCP tool stubs from an OpenAPI 3.x spec.
Reads from a local JSON file or URL and prints Python tool definitions
to stdout that you can paste into your src/tools/ file.

Usage:
  python scripts/openapi_to_mcp.py ./openapi.json
  python scripts/openapi_to_mcp.py https://petstore3.swagger.io/api/v3/openapi.json
"""

import json
import re
import sys
import httpx


def to_snake_case(s: str) -> str:
    s = re.sub(r"([A-Z])", r"_\1", s).lower()
    return s.lstrip("_")


def to_tool_name(operation_id: str | None, method: str, path: str) -> str:
    if operation_id:
        return to_snake_case(operation_id)
    parts = [p for p in re.sub(r"[{}]", "", path).split("/") if p]
    return f"{method}_{'_'.join(parts)}"


def main():
    if len(sys.argv) < 2:
        print("Usage: python scripts/openapi_to_mcp.py <path-or-url>", file=sys.stderr)
        sys.exit(1)

    arg = sys.argv[1]

    if arg.startswith("http"):
        response = httpx.get(arg)
        response.raise_for_status()
        raw = response.text
    else:
        with open(arg, "r", encoding="utf-8") as f:
            raw = f.read()

    spec = json.loads(raw)
    tools: list[str] = []

    for path, methods in (spec.get("paths") or {}).items():
        for method, op in methods.items():
            if method not in ("get", "post", "put", "patch", "delete"):
                continue

            tool_name = to_tool_name(op.get("operationId"), method, path)
            description = op.get("summary") or op.get("description") or f"{method.upper()} {path}"
            description = description.replace('"', '\\"')

            properties: dict = {}
            required: list[str] = []

            for param in op.get("parameters") or []:
                if param.get("in") in ("path", "query"):
                    schema = param.get("schema") or {}
                    prop: dict = {"type": schema.get("type", "string")}
                    if param.get("description"):
                        prop["description"] = param["description"]
                    if schema.get("enum"):
                        prop["enum"] = schema["enum"]
                    properties[param["name"]] = prop
                    if param.get("required"):
                        required.append(param["name"])

            body_schema = (
                (op.get("requestBody") or {})
                .get("content", {})
                .get("application/json", {})
                .get("schema", {})
            )
            if body_schema.get("properties"):
                for prop_name, prop_def in body_schema["properties"].items():
                    entry: dict = {"type": prop_def.get("type", "string")}
                    if prop_def.get("description"):
                        entry["description"] = prop_def["description"]
                    properties[prop_name] = entry
                if op.get("requestBody", {}).get("required") and body_schema.get("required"):
                    required.extend(body_schema["required"])

            props_json = json.dumps(properties, indent=8)
            required_json = json.dumps(list(dict.fromkeys(required)))

            tools.append(
                f'    {{\n'
                f'        "name": "{tool_name}",\n'
                f'        "description": "{description}",\n'
                f'        "inputSchema": {{\n'
                f'            "type": "object",\n'
                f'            "properties": {props_json},\n'
                f'            "required": {required_json},\n'
                f'        }},\n'
                f'    }},'
            )

    print(f"# Auto-generated by openapi_to_mcp.py — review before using")
    print(f"# Source: {arg}")
    print()
    print("GENERATED_TOOLS = [")
    print("\n".join(tools))
    print("]")
    print()
    print(
        "async def handle_generated_tool(name: str, args: dict) -> dict:\n"
        "    # TODO: implement each tool handler\n"
        "    # Pattern: httpx.get(f\"{BASE_URL}/your-endpoint\", headers=auth_headers())\n"
        "    raise NotImplementedError(f\"Not implemented: {name}\")\n"
    )


if __name__ == "__main__":
    main()
